In [16]:
import numpy as np

In [17]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
s = slice(2, 8, 2)
print(s, type(s))

slice(2, 8, 2) <class 'slice'>


In [20]:
print(a[s])

[2 4 6]


In [21]:
print(a[3])

3


In [22]:
print(a[3:])

[3 4 5 6 7 8 9]


In [23]:
print(a[:3])

[0 1 2]


In [24]:
a = np.arange(1, 10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(a[...,1])

[2 5 8]


In [29]:
print(a[...,1:])

[[2 3]
 [5 6]
 [8 9]]


In [28]:
print(a[1,...])

[4 5 6]


In [30]:
a = np.arange(1,7).reshape(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [31]:
b = a[[0,1,2],[0,1,0]]
print(b)

[1 4 5]


In [33]:
a = np.array([[0,1,2], [3,4,5], [6,7,8], [9,10,11]])
print(a)
print('-' * 20)

rows = np.array([[0,0], [3,3]])
cols = np.array([[0,2], [0,2]])

b = a[rows, cols]
print(b)
print('-' * 20)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
--------------------
[[ 0  2]
 [ 9 11]]
--------------------


In [34]:
a = np.arange(32).reshape(8, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [35]:
print(a[np.ix_([1,5,7,2], [0,3,1,2])])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [36]:
a = np.array([
    [0, 0, 0],
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30]
])

print(a)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [37]:
b = [[0, 1, 2]]
print(a + b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [38]:
b = [0, 1]
print(a + b)

ValueError: operands could not be broadcast together with shapes (4,3) (2,) 