In [2]:
import numpy as np

a = np.arange(24)

print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [4]:
b = a.reshape(2, 3, 4)
print(b)
print(b.ndim)

print(b.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
(2, 3, 4)


In [5]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

print('-' * 20)

a.shape = (3,2)
print(a)

[[1 2 3]
 [4 5 6]]
--------------------
[[1 2]
 [3 4]
 [5 6]]


In [7]:
a1 = np.array([1,2,3,4,5], dtype=int)
print(a1.dtype)
print(a1.itemsize)

a2 = np.array([1,2,3,4,5], dtype=float)
print(a2.dtype)
print(a2.itemsize)

int32
4
float64
8


In [11]:
a = np.empty((3, 2), dtype='i4')
print(a)

[[2036429426 1701602592]
 [1953391981  168439411]
 [ 538976288 1634885968]]


In [12]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [13]:
a = np.zeros((3, 5), dtype=int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [15]:
a = np.zeros((3, 2), dtype=[('x', 'f4'), ('y', 'i4')])
print(a)

print('-' * 20)

a[0][0]['x'] = 1.23
a[0][0]['y'] = 1.23

print(a)

[[(0., 0) (0., 0)]
 [(0., 0) (0., 0)]
 [(0., 0) (0., 0)]]
--------------------
[[(1.23, 1) (0.  , 0)]
 [(0.  , 0) (0.  , 0)]
 [(0.  , 0) (0.  , 0)]]


In [16]:
a = np.ones(5)
print(a)
print(a.dtype)

[1. 1. 1. 1. 1.]
float64


In [17]:
a = np.ones((3, 5), dtype=int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [19]:
a = np.full(5, fill_value=999)
print(a)
print(a.dtype)

[999 999 999 999 999]
int32


In [21]:
a = np.eye(10, dtype=int)
print(a)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]
